modify blog-dev for accepting options

diff --git a/blog-dev b/blog-dev
--- a/blog-dev
+++ b/blog-dev
@@ -1,8 +1,59 @@
-#!/usr/bin/bash
+#!/bin/bash
 set -e
-# start up containers
-docker start blog-redis
-docker start blog-mongo
-# start poetry env
-cd ~/repos/blog
-poetry run python app.py
+
+reset=false
+new=false
+rm=false
+
+while getopts ":rnm" opt; do
+  case ${opt} in
+    r )
+      reset=true
+      ;;
+    n )
+      new=true
+      ;;
+    m )
+      rm=true
+      ;;
+    \? )
+      echo "Usage: $0 [-r] [-n] [-m]"
+      exit 1
+      ;;
+  esac
+done
+
+# Check if more than one option is specified
+if [ "$((${reset} + ${new} + ${rm}))" -gt 1 ]; then
+  echo "Error: Only one of -r, -n, or -m can be specified at a time."
+  exit 1
+fi
+
+if [ "$reset" = true ]; then
+  (docker stop blog-redis || true) > /dev/null
+  (docker rm blog-redis || true) > /dev/null
+  (docker stop blog-mongo || true) > /dev/null
+  (docker rm blog-mongo || true) > /dev/null
+  docker run -d --name blog-redis -p 6379:6379 redis:latest --requirepass "12345678" > /dev/null
+  docker run -d --name blog-mongo -p 27017:27017 -e MONGO_INITDB_ROOT_USERNAME=root -e MONGO_INITDB_ROOT_PASSWORD=12345678 mongo:latest > /dev/null
+  echo "containers reset."
+elif [ "$new" = true ]; then
+  docker run -d --name blog-redis -p 6379:6379 redis:latest --requirepass "12345678" > /dev/null
+  docker run -d --name blog-mongo -p 27017:27017 -e MONGO_INITDB_ROOT_USERNAME=root -e MONGO_INITDB_ROOT_PASSWORD=12345678 mongo:latest > /dev/null
+  echo "containers created."
+elif [ "$rm" = true ]; then
+  (docker stop blog-redis || true) > /dev/null
+  (docker rm blog-redis || true) > /dev/null
+  (docker stop blog-mongo || true) > /dev/null
+  (docker rm blog-mongo || true) > /dev/null
+  echo "containers removed."
+else
+  # start up containers
+  docker start blog-redis > /dev/null
+  docker start blog-mongo > /dev/null
+  echo "containers started."
+  # start poetry env
+  cd /home/hank/my-github-repo/BlogYourWay
+  poetry run python app.py
+fi
+
